### ISSUE TITLE
feature request - faster furnace carts

### ISSUE THREAD

**Issue by SFort** [ndrp/faster-minecarts#1]
Thanks for the mod always exited to see minecarts made better.
Although furnace carts are still way too slow
Would you please consider making them faster or having a upgraded furnace cart?
<details>
<summary>
(i tried using the mod with fabrication which just bugged it)</summary>

![](https://user-images.githubusercontent.com/1879846/105021580-976f6980-5a40-11eb-84cd-032a01a36cd9.gif)

</details>

**Comment by faultycore** [comment]
Thanks for pointing that out. I actually thought that the mod would increase the speed of all minecarts since I inject in a method of AbstractMinecartEntity from which all minecarts should inherit, but it turns out that FurnaceMinecartEntity overwrites it with an even slower speed. It should be easy to also apply it to furnace minecarts though.

**Comment by faultycore** [comment]
Furnace carts fixed in version 1.0.1

**Comment by faultycore** [comment]
Will also look into what causes the incompatibility with Fabrication.

**Comment by faultycore** [comment]
>  (i tried using the mod with fabrication which just bugged it)

Could you describe what was bugged? From what I can gather Fabrication should simply overwrite what Faster Minecarts does to furnace carts. In fact, it might be beneficial to use Fabrication alongside Faster Minecarts, since Fabrication has some other improvements for furnace carts while I simply increase the max speed at the moment.

**Comment by SFort** [comment]
thanks for the quick fix  
after testing a bit more(with the new version) 
with fabrication hyperspeed carts disabled the issue is still there as long as fabrication is installed

the arrow to the left of "(i tried using the mo...)" indicades a collapsable menu in github
clicking on the text should show a gif of a furnace cart constantly pinging back and forth between two turns.
which is what happens consistently untill either
- minecart runs out of fuel
- fabrication makes the furnace cart de-rail

i'd say best steps to reploduce is make rail looping with a few extra turns and the furnace cart is bound to get stuck

**Comment by SFort** [comment]
looking at the fabrication mixin. if you have any of the cart mixins enabled it will cause the issue otherwise it works fine(options being furnace_minecart_pushing, hyperspeed_furnace_minecart, furnace_minecart_any_fuel)
I think this is something that needs to be fixed fabrication side [#89](https://github.com/unascribed/Fabrication/issues/89).
Thanks again

**Comment by faultycore** [comment]
Thanks for your extensive testing and sorry for the late reply, GitHub somehow only decides to send me emails 3 hours after someone commented on an issue. I think too that it must be a Fabrication issue, since Fabrication simply @overwrites everything cart related, so Faster Minecarts should basically do nothing for furnace carts if Fabrication with the minecart options enabled is present.

**Comment by SFort** [comment]
![](https://user-images.githubusercontent.com/1879846/105212555-878d7d80-5b45-11eb-94c0-324b222ecbd9.gif)
(not really a big deal just thought you might wanna know)

**Comment by faultycore** [comment]
At the moment this behaviour is expected, because I haven't really discriminated between curves that actually change the direction of travel and curves that are basically straight diagonal tracks. But I will see if I can find a way to change that, though I'd like to have this mod have as little of an impact on performance as possible (overall the impact will be marginal anyway, but still).

**Comment by SFort** [comment]
@ndrp dam looks like #2 missed you by 5min well, guess you'll see it eventually just hope you don't write another solution by then
